from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from .tools.custom_tool import SendOutLookMail, DatadogLogsSearch

# devx api 호출
from .devx_llm_wrapper import llm

@CrewBase
class DatadogMonitoringV2():
    """DatadogMonitoringV2 crew generated by Meta-Agent"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    def __init__(self, mcp_tools=None):
        self.mcp_tools = mcp_tools or []

    def _get_mcp_tool_by_name(self, name: str):
        for tool in self.mcp_tools:
            if tool.name == name:
                return tool
        return None

    def _get_mcp_tools_by_names(self, names: list[str]):
        res = []
        for name in names:
            tool = self._get_mcp_tool_by_name(name)
            if tool:
                res.append(tool)
        return res

    @agent
    def datadog_log_retrieval_specialist(self) -> Agent:
        mcp_tools = self._get_mcp_tools_by_names(["search_datadog_logs", "search_datadog_apm"])
        tools = mcp_tools if mcp_tools else [DatadogLogsSearch()]
        return Agent(
            config=self.agents_config['datadog_log_retrieval_specialist'],
            tools=tools,
            verbose=True,
            reasoning=False,
            max_reasoning_attempts=None,
            inject_date=True,
            allow_delegation=False,
            max_iter=20,
            max_rpm=None,
            max_execution_time=None,
            llm=llm
        )
    
    @agent
    def application_error_analysis_expert(self) -> Agent:
        return Agent(
            config=self.agents_config['application_error_analysis_expert'],
            verbose=True,
            reasoning=False,
            max_reasoning_attempts=None,
            inject_date=True,
            allow_delegation=False,
            max_iter=20,
            max_rpm=None,
            max_execution_time=None,
            llm=llm
        )
    
    @agent
    def technical_report_writer(self) -> Agent:
        return Agent(
            config=self.agents_config['technical_report_writer'],
            verbose=True,
            reasoning=False,
            max_reasoning_attempts=None,
            inject_date=True,
            allow_delegation=False,
            max_iter=20,
            max_rpm=None,
            max_execution_time=None,
            llm=llm
        )
    
    @agent
    def notification_dispatcher(self) -> Agent:
        mcp_tools = self._get_mcp_tools_by_names(["send_outlook_email", "send_google_email"])
        tools = mcp_tools if mcp_tools else [SendOutLookMail()]
        return Agent(
            config=self.agents_config['notification_dispatcher'],
            tools=tools,
            verbose=True,
            reasoning=False,
            max_reasoning_attempts=None,
            inject_date=True,
            allow_delegation=False,
            max_iter=20,
            max_rpm=None,
            max_execution_time=None,
            llm=llm
        )
    
    @task
    def fetch_datadog_logs(self) -> Task:
        return Task(
            config=self.tasks_config['fetch_datadog_logs'],
            markdown=False
        )

    @task
    def analyze_application_logs(self) -> Task:
        return Task(
            config=self.tasks_config['analyze_application_logs'],
            markdown=False
        )

    @task
    def generate_log_report(self) -> Task:
        return Task(
            config=self.tasks_config['generate_log_report'],
            markdown=False
        )

    @task
    def send_report_via_email(self) -> Task:
        return Task(
            config=self.tasks_config['send_report_via_email'],
            markdown=False
        )

    @crew
    def crew(self) -> Crew:
        """Creates the DatadogMonitoringV2 crew"""
        return Crew(
            agents=self.agents, # 자동으로 @agent가 붙은 메서드들을 수집
            tasks=self.tasks,   # 자동으로 @task가 붙은 메서드들을 수집
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, # 관리자 에이전트 도입 등 필요시 변경
        )
