#!/usr/bin/env python
import os
import sys
from datadog_monitoring_v2.crew import DatadogMonitoringV2

# This main file is automatically generated by the Meta-Agent.

def run():
    """Run the crew."""
    inputs = {
        "output_path": "./output/output.md",
        "time_range": "last 1 hours",
        "datadog_query": "service:erody-bo-backend-20 status:error",
        "search_option": "logs",
        "limit": "3",
    }
    try:
        DatadogMonitoringV2().crew().kickoff(inputs=inputs)
    except Exception as e:
        raise Exception(f"An error occurred while running the crew: {e}")

