#!/usr/bin/env python
import os
import sys
from crewai_tools import MCPServerAdapter
from datadog_monitoring_v2.crew import DatadogMonitoringV2

# This main file is automatically generated by the Meta-Agent.

def run():
    """Run the crew."""
    inputs = {
        "output_path": "./output/output.md",
        "time_range": "last 1 hours",
        'datadog_query': 'service:erody-bo-backend-20 @http.status_code:[400 TO 599]',
        "search_option": "logs",
        "limit": "10",
    }
    
    # Connect to the shared MCP server via SSE
    # The Celery worker will start this server at localhost:8012
    server_params = {
        "url": os.environ.get("SHARED_MCP_SERVER_URL", "http://localhost:8012/sse"),
        "transport": "sse"
    }
    
    try:
        print(f"[MCP Client] Connecting to shared MCP server at {server_params['url']}...")
        with MCPServerAdapter(server_params) as tools:
            print(f"[MCP Client] Connected to shared MCP server. Discovered {len(tools)} tools.")
            DatadogMonitoringV2(mcp_tools=tools).crew().kickoff(inputs=inputs)
    except Exception as e:
        print(f"[Warning] Failed to connect to shared MCP server ({e}). Falling back to custom_tool.py local executions.", flush=True)
        DatadogMonitoringV2().crew().kickoff(inputs=inputs)
