from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task

# devx api 호출
from .devx_llm_wrapper import llm

# Uncomment the following line to use an example of a custom tool
# from my_auto_crew.tools.custom_tool import MyCustomTool

# Check our tools documentations for more information on how to use them
# from crewai_tools import SerperDevTool /

@CrewBase
class MyAutoCrew():
    """MyAutoCrew crew generated by Meta-Agent"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    @agent
    def researcher(self) -> Agent:
        return Agent(
            config=self.agents_config['researcher'],
            verbose=True,
            llm=llm
        )

    @agent
    def writer(self) -> Agent:
        return Agent(
            config=self.agents_config['writer'],
            verbose=True,
            llm=llm
        )

    @task
    def research_task(self) -> Task:
        return Task(
            config=self.tasks_config['research_task'],
        )

    @task
    def write_task(self) -> Task:
        return Task(
            config=self.tasks_config['write_task'],
        )

    @crew
    def crew(self) -> Crew:
        """Creates the MyAutoCrew crew"""
        return Crew(
            agents=self.agents, # 자동으로 @agent가 붙은 메서드들을 수집
            tasks=self.tasks,   # 자동으로 @task가 붙은 메서드들을 수집
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, # 관리자 에이전트 도입 등 필요시 변경
        )
