#!/usr/bin/env python
import os
import sys
from crewai_tools import MCPServerAdapter
from datadog_monitoring_v3.crew import DatadogMonitoringV3

# This main file is automatically generated by the Meta-Agent.

def run():
    """Run the crew."""
    inputs = {
        'datadog_query': '여기에 datadog_query 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'time_range': '여기에 time_range 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'search_option': '여기에 search_option 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'output_path': '여기에 output_path 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'limit': '여기에 limit 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
    }

    # Connect to the shared MCP server via SSE
    # The Celery worker will start this server at localhost:8012
    server_params = {
        "url": os.environ.get("SHARED_MCP_SERVER_URL", "http://localhost:8012/sse"),
        "transport": "sse"
    }

    try:
        print(f"[MCP Client] Connecting to shared MCP server at {server_params['url']}...")
        with MCPServerAdapter(server_params) as tools:
            print(f"[MCP Client] Connected to shared MCP server. Discovered {len(tools)} tools.")
            DatadogMonitoringV3(mcp_tools=tools).crew().kickoff(inputs=inputs)
    except Exception as e:
        print(f"[Warning] Failed to connect to shared MCP server ({e}). Falling back to custom_tool.py local executions.", flush=True)
        DatadogMonitoringV3().crew().kickoff(inputs=inputs)

