#!/usr/bin/env python
import sys
from datadog_monitoring_v3.crew import DatadogMonitoringV3

# This main file is automatically generated by the Meta-Agent.

def run():
    """Run the crew."""
    inputs = {
        'datadog_query': '여기에 datadog_query 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'output_path': '여기에 output_path 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'limit': '여기에 limit 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'search_option': '여기에 search_option 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
        'time_range': '여기에 time_range 값을 입력하세요', # TODO: 런타임에 실제 값으로 치환
    }
    try:
        DatadogMonitoringV3().crew().kickoff(inputs=inputs)
    except Exception as e:
        raise Exception(f"An error occurred while running the crew: {e}")

