from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task

# devx api 호출
from .devx_llm_wrapper import llm

# Uncomment the following line to use an example of a custom tool
# from my_auto_crew2.tools.custom_tool import MyCustomTool

# Check our tools documentations for more information on how to use them
# from crewai_tools import SerperDevTool

@CrewBase
class MyAutoCrew2():
    """MyAutoCrew2 crew generated by Meta-Agent"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    @agent
    def agent1(self) -> Agent:
        return Agent(
            config=self.agents_config['agent1'],
            verbose=True,
            llm=llm
        )

    @agent
    def agent2(self) -> Agent:
        return Agent(
            config=self.agents_config['agent2'],
            verbose=True,
            llm=llm
        )

    @agent
    def agent3(self) -> Agent:
        return Agent(
            config=self.agents_config['agent3'],
            verbose=True,
            llm=llm
        )

    @task
    def task1(self) -> Task:
        return Task(
            config=self.tasks_config['task1'],
        )

    @task
    def task2(self) -> Task:
        return Task(
            config=self.tasks_config['task2'],
        )

    @task
    def task3(self) -> Task:
        return Task(
            config=self.tasks_config['task3'],
        )

    @crew
    def crew(self) -> Crew:
        """Creates the MyAutoCrew2 crew"""
        return Crew(
            agents=self.agents, # 자동으로 @agent가 붙은 메서드들을 수집
            tasks=self.tasks,   # 자동으로 @task가 붙은 메서드들을 수집
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, # 관리자 에이전트 도입 등 필요시 변경
        )
