#!/usr/bin/env python
import sys
from datadog_monitoring.crew import DatadogMonitoring

# This main file is automatically generated by the Meta-Agent.

def run():
    """Run the crew."""
    inputs = {
        'recipient_email': 'jck@shinsegae.com', # TODO: 런타임에 실제 값으로 치환
        'time_range': 'last 1 hour', # TODO: 런타임에 실제 값으로 치환
        'datadog_query': 'service:erody-bo-backend-20 @http.status_code:[400 TO 599]', # TODO: 런타임에 실제 값으로 치환
        'output_path': './output/output.md', # TODO: 런타임에 실제 값으로 치환
        'limit': '5', # TODO: 런타임에 실제 값으로 치환
    }
    try:
        DatadogMonitoring().crew().kickoff(inputs=inputs)
    except Exception as e:
        raise Exception(f"An error occurred while running the crew: {e}")