from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from crewai_tools import WebsiteSearchTool
from datadog_log_monitor_reporter.tools.custom_tool import DatadogLogsSearch

# devx api 호출
from .devx_llm_wrapper import llm

@CrewBase
class DatadogLogMonitorReporter():
    """DatadogLogMonitorReporter crew generated by Meta-Agent"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    @agent
    def datadog_log_retrieval_specialist(self) -> Agent:
        return Agent(
            config=self.agents_config['datadog_log_retrieval_specialist'],
            tools=[DatadogLogsSearch(), WebsiteSearchTool()],
            verbose=True,
            llm=llm
        )
    
    @agent
    def application_error_analysis_expert(self) -> Agent:
        return Agent(
            config=self.agents_config['application_error_analysis_expert'],
            verbose=True,
            llm=llm
        )
    
    @agent
    def technical_report_writer(self) -> Agent:
        return Agent(
            config=self.agents_config['technical_report_writer'],
            verbose=True,
            llm=llm
        )
    
    @agent
    def notification_dispatcher(self) -> Agent:
        return Agent(
            config=self.agents_config['notification_dispatcher'],
            verbose=True,
            llm=llm
        )
    
    @task
    def fetch_datadog_logs(self) -> Task:
        return Task(
            config=self.tasks_config['fetch_datadog_logs'],
        )

    @task
    def analyze_application_logs(self) -> Task:
        return Task(
            config=self.tasks_config['analyze_application_logs'],
        )

    @task
    def generate_log_report(self) -> Task:
        return Task(
            config=self.tasks_config['generate_log_report'],
        )

    @task
    def send_report_via_email(self) -> Task:
        return Task(
            config=self.tasks_config['send_report_via_email'],
        )

    @crew
    def crew(self) -> Crew:
        """Creates the DatadogLogMonitorReporter crew"""
        return Crew(
            agents=self.agents, # 자동으로 @agent가 붙은 메서드들을 수집
            tasks=self.tasks,   # 자동으로 @task가 붙은 메서드들을 수집
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, # 관리자 에이전트 도입 등 필요시 변경
        )
