[project]
name = "datadog_monitoring"
version = "0.1.0"
description = "datadog_monitoring using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[bedrock,tools]==1.14.7",
]

[project.scripts]
datadog_monitoring = "datadog_monitoring.main:run"
run_crew = "datadog_monitoring.main:run"
train = "datadog_monitoring.main:train"
replay = "datadog_monitoring.main:replay"
test = "datadog_monitoring.main:test"
run_with_trigger = "datadog_monitoring.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
